# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FilterShowcase' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'AlamofireImage', '~> 3.3'
    pod 'Toast', '~> 4.0.0'
    pod 'RxCocoa'
    pod 'RxSwift'
    use_frameworks!
    pod 'Fabric'
    pod 'Crashlytics'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            end
        end
    end
end
